# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build&Publish Package

on: [ workflow_dispatch ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ctp-version: [ "6315", "6319", "651", "661", "667", "669" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Building Package
        working-directory: ctp-${{ matrix.ctp-version }}
        run: hatch build
      - name: Store Package
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distribution
          path: dist

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        ctp-version: [ "667", "669" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Building Package
        working-directory: ctp-${{ matrix.ctp-version }}
        run: hatch build
      - name: Store Package
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distribution
          path: dist

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        ctp-version: [ "6315", "6319", "651", "661", "667", "669" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Building Package
        working-directory: ctp-${{ matrix.ctp-version }}
        run: hatch build
      - name: Store Package
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distribution
          path: dist

  publish-dist:
    needs:
      - build-linux
      - build-windows
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hatch
      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: python-package-distribution
          path: dist/
      - name: Publish a Python distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
